# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

try:
    from . import mesh_service_pb2 as mesh__service__pb2
except ImportError:
    import mesh_service_pb2 as mesh__service__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in mesh_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class NodeAgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
            "/agent_mesh.NodeAgentService/Ping",
            request_serializer=mesh__service__pb2.PingRequest.SerializeToString,
            response_deserializer=mesh__service__pb2.PingResponse.FromString,
            _registered_method=True,
        )
        self.StreamTelemetry = channel.unary_stream(
            "/agent_mesh.NodeAgentService/StreamTelemetry",
            request_serializer=mesh__service__pb2.TelemetryRequest.SerializeToString,
            response_deserializer=mesh__service__pb2.TelemetryUpdate.FromString,
            _registered_method=True,
        )
        self.StreamCompletion = channel.unary_stream(
            "/agent_mesh.NodeAgentService/StreamCompletion",
            request_serializer=mesh__service__pb2.CompletionRequestProto.SerializeToString,
            response_deserializer=mesh__service__pb2.CompletionChunkProto.FromString,
            _registered_method=True,
        )
        self.ControlContainer = channel.unary_unary(
            "/agent_mesh.NodeAgentService/ControlContainer",
            request_serializer=mesh__service__pb2.ContainerControlRequest.SerializeToString,
            response_deserializer=mesh__service__pb2.ContainerControlResponse.FromString,
            _registered_method=True,
        )


class NodeAgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Ultra-fast ping check with Round-Trip Time"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamTelemetry(self, request, context):
        """Bidirectional streaming telemetry (hardware stats, GPU VRAM, loaded models, queues)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamCompletion(self, request, context):
        """Sub-millisecond token streaming proxy"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ControlContainer(self, request, context):
        """Remote Docker container lifecycle management"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NodeAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Ping": grpc.unary_unary_rpc_method_handler(
            servicer.Ping,
            request_deserializer=mesh__service__pb2.PingRequest.FromString,
            response_serializer=mesh__service__pb2.PingResponse.SerializeToString,
        ),
        "StreamTelemetry": grpc.unary_stream_rpc_method_handler(
            servicer.StreamTelemetry,
            request_deserializer=mesh__service__pb2.TelemetryRequest.FromString,
            response_serializer=mesh__service__pb2.TelemetryUpdate.SerializeToString,
        ),
        "StreamCompletion": grpc.unary_stream_rpc_method_handler(
            servicer.StreamCompletion,
            request_deserializer=mesh__service__pb2.CompletionRequestProto.FromString,
            response_serializer=mesh__service__pb2.CompletionChunkProto.SerializeToString,
        ),
        "ControlContainer": grpc.unary_unary_rpc_method_handler(
            servicer.ControlContainer,
            request_deserializer=mesh__service__pb2.ContainerControlRequest.FromString,
            response_serializer=mesh__service__pb2.ContainerControlResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "agent_mesh.NodeAgentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("agent_mesh.NodeAgentService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class NodeAgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/agent_mesh.NodeAgentService/Ping",
            mesh__service__pb2.PingRequest.SerializeToString,
            mesh__service__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamTelemetry(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/agent_mesh.NodeAgentService/StreamTelemetry",
            mesh__service__pb2.TelemetryRequest.SerializeToString,
            mesh__service__pb2.TelemetryUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamCompletion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/agent_mesh.NodeAgentService/StreamCompletion",
            mesh__service__pb2.CompletionRequestProto.SerializeToString,
            mesh__service__pb2.CompletionChunkProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ControlContainer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/agent_mesh.NodeAgentService/ControlContainer",
            mesh__service__pb2.ContainerControlRequest.SerializeToString,
            mesh__service__pb2.ContainerControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
